version: "3.3"
services:
  mongodb_container:
    image: mongo:latest
    container_name: db_for_testing
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: db_for_testing
    ports:
      - 27017:27017