name: Deploy to Heroku (Backend)

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/api.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add api remote origin
        run: git remote add heroku-backend https://heroku:${{ secrets.HEROKU_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_BACKEND_APP_NAME }}.git
      - name: Deploy api to Heroku
        run: git push heroku-backend `git subtree split --prefix api main`:refs/heads/main --force
